/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Trip;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import model.BookTableModel;

/**
 *
 * @author andri
 */
public class BookTripPanel extends javax.swing.JPanel {
    
    private final List<Trip> trips;
    private JTable table;
    
    /**
     * Creates new form BookTripPanel
     * @param results
     */
    public BookTripPanel(List<Trip> results) {
        trips = results;
        
    }
    
    public JScrollPane Show(){
       TableModel model = new BookTableModel(trips);
       table = new JTable(model);
       table.removeColumn(table.getColumnModel().getColumn(0)); 
       table.removeColumn(table.getColumnModel().getColumn(1)); 
       table.removeColumn(table.getColumnModel().getColumn(4));
       table.removeColumn(table.getColumnModel().getColumn(4));
       table.removeColumn(table.getColumnModel().getColumn(5));
       table.removeColumn(table.getColumnModel().getColumn(5));
       table.removeColumn(table.getColumnModel().getColumn(5));
       table.removeColumn(table.getColumnModel().getColumn(5));
       JScrollPane panel = new JScrollPane(table);
       return panel;
    }
        
    public Trip getSelectedRow(){
        if(table != null) {
            int index = table.getSelectedRow();
            if(index == -1) return null;
            return trips.get(index);
        }
        return null;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
